### ISSUE TITLE
Missing browser specific styles

### ISSUE THREAD

**Issue by klbrisson** [Financial-Times/o-forms#102]
After updating, it looks like browser specific styles were removed. Before updating, we saw styles such as "background-image: none\9;" and "@media \0screen". These styles are no longer found anywhere in the file after updating. Was there a reason these styles were removed? 

This is causing an issue with .o-forms-select where the image for the drop down icon is still being added for IE9, so there are 2 icons since the default button cannot be hidden in IE9. 

Here's the code for o-forms-select before and after updating.
Old code:
```css
.o-forms-select {
    cursor:pointer;
    background-image:url()  -- (didn't include url for readability)
    background-position:right center;
    background-position:right 5px center;
    background-repeat:no-repeat;
    background-origin:border-box;
    background-size:19px;
    padding-right:24px;
    padding-top:6px;
    line-height:110%;
    padding-bottom:6px\9;
    padding-right:5px\9;
    background-image:none\9;  -- without this style, duplicate icons appear in IE9
    text-indent:.01px;
    text-overflow:
}
```

New code after updating - browser specific styling is missing:
```css
.o-forms-select {
    cursor: pointer;
    background-image: url();    -- (didn't include url for readability)
    background-position: right center;
    background-position: right 5px center;
    background-repeat: no-repeat;
    background-origin: border-box;
    background-size: 19px;
    padding-right: 24px;
    padding-top: 6px;
    line-height: 110%;
    text-indent: .01px;
    text-overflow: ''
}
```
