### ISSUE TITLE
Styling "indeterminate" checkboxes

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/o-forms#232]
Should o-forms add styling for [indeterminate state checkboxes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Indeterminate_state_checkboxes) I think it would be a case of targetting the [`:indeterminate`](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate) psuedo selector [here](https://github.com/Financial-Times/o-forms/blob/51059fc3232840e1ed2e7e3e89809a19cde1a2a4/src/scss/mixins/_radio-checkbox.scss#L38-L46) adding

```scss
&:indeterminate + .#{$class}__label::after {
	@include oIconsGetIcon('minus', _oFormsGet('checkbox-radio-checked-icon'), $_o-forms-radiocheckbox-default-size);
	background-color: _oFormsGet('checkbox-radio-checked-background');
}
```

Using the "minus" icon to get this example:
<img width="294" alt="screenshot 2018-11-05 14 43 00" src="https://user-images.githubusercontent.com/11544418/48005080-7134ac00-e10a-11e8-849d-903d70157cd3.png">
