### ISSUE TITLE
"unskin" class to make a text field look like text

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-forms#83]
- remove background
- remove border
- remove focus state
- remove left/right spacing
- keep top/bottom spacing to keep the vertical rhythm in a series of label/inputs elements

====

- [x] Create class
- [x] Create mixin
- [x] Documentation
- [ ] Tests

**Comment by kaelig** [comment]
Here's the code used by membership to unskin a disabled field:

```scss
.o-ft-forms__field--text:disabled {
    border-width: 0;
    background-color: transparent;
    color: #333;
    padding-left: 0;
    padding-right: 0;
    // for iOS
    -webkit-text-fill-color: #333;
    opacity: 1;
}
```

**Comment by kaelig** [comment]
### Class:

`.o-forms-unskin`

https://github.com/Financial-Times/o-ft-forms/blob/v1/src/scss/unskin.scss

### Mixin:

`@include oFormsUnskin`

https://github.com/Financial-Times/o-ft-forms/blob/v1/src/scss/_mixins.scss#L41

**Comment by kaelig** [comment]
@jamesnicholls @Thurst-ft could have a look at this and let me know if that looks good for your use cases?

**Comment by jamesnicholls** [comment]
@kaelig I guess the colours shouldn't be hard-coded. I've updated the Membership code to use the `o-ft-typography-body` colour use-case. Also, I added `appearance: none` (and some associated hackery for Firefox) so that the dropdown arrow doesn't appear if this class is applied to a select.

**Comment by kaelig** [comment]
Sorry, the line has changed.

Here's the mixin's code I wanted to discuss:

```scss
/// Unskin a field entirely, but keep its structure intact
@mixin oFormsUnskin {
	-moz-appearance: none !important;
	-webkit-appearance: none !important;
	border: 0 !important;
	background-color: transparent !important;
	color: #333333 !important;
	padding-left: 0 !important;
	padding-right: 0 !important;

	// for iOS
	-webkit-text-fill-color: #333333 !important;
	opacity: 1 !important;
}
```
