### ISSUE TITLE
Proposal: remove hover state on checkboxes/radio inputs

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-forms#91]
After our discussion during this morning's Design Origami meeting, I've tried to re-implement the hover state properly. There's been a few changes of design in between (added proper focus states, new colors), and now I remember why I had removed the hover state on checkboxes and radio buttons from the v1 branch: it's just complicating things.

Here is the Sass code necessary to have hover states built in on checkboxes and buttons with the new design specifications:

```scss
// Apply different border colour to checkboxes and radio labels on hover  / unchecked states
#{$o-hoverable-if-hover-enabled} #{$checkbox}:not(:checked):hover + #{$label}:before,
#{$o-hoverable-if-hover-enabled} #{$radio}:not(:checked):hover + #{$label}:before {
	border-color: oColorsGetColorFor(o-forms-field-focus, border);
}
// Apply different border colour to checkboxes and radio labels on hover / checked states
#{$o-hoverable-if-hover-enabled} #{$checkbox}:checked:hover + #{$label}:before,
#{$o-hoverable-if-hover-enabled} #{$radio}:checked:hover + #{$label}:before {
	border-color: oColorsGetColorFor(o-forms-field-, border);
}
```

- This will compile to a series of selectors (especially the `:not(:checked)`) that are very costly in terms of code maintainability.
- It makes recreating that experience much harder for a product that would like to re-implement it an other way in case they have technical limitations.
- It has no added value for touch users

For the sake of keeping things simple, I implore the gods of design and UX to accept to drop this hover state :)
